name: Build app and deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 监听 master 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境是 Ubuntu

    steps:
      # 获取源码
      - name: Checkout code
        uses: actions/checkout@v3

       #安装Node13
      - name: use Node.js 12.14.1
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      
      # 安装依赖
      - name: npm install
        run: npm install

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 打包
      - name: Build the project
        run: npm run build  # 根据你的项目配置构建静态文件，假设输出目录为 public 或 dist

      # 推送构建文件到 gh-pages 分支
      - name: Deploy to GitHub Pages
        run: |
          cd public
          
          # 初始化 git 仓库
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          
          # 配置 git 用户
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 添加所有文件并提交
          git add -A
          git commit -m "Deploy to GitHub Pages"
          
          # 强制推送到 gh-pages 分支
          git push -f origin master:gh-pages  # 这会将 public 目录内容推送到 gh-pages 分支

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动提供的 GitHub Token，用于身份验证
